# Generated by Django 4.1.5 on 2023-02-06 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='refresh_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, verbose_name='refresh token'),
        ),
    ]
