# Generated by Django 4.1.5 on 2023-02-01 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='refresh_token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('access_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=256, null=True, verbose_name='refresh token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tokens',
                'verbose_name_plural': 'tokens',
            },
        ),
    ]
