# Generated by Django 4.1.5 on 2023-01-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmsdata',
            name='mms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.mms', verbose_name='mms'),
        ),
    ]
